"""
changelog — Auto-generate CHANGELOG.md from openspec/changes/ HDUs.

Scans proposal.md in each HDU directory, extracts Why + What Changes,
and generates a user-facing changelog grouped by release tags or manual sections.
"""
import os
import re
from pathlib import Path
from typing import Optional


def _find_openspec_dir() -> Optional[Path]:
    """Walk up from cwd to find openspec/changes/."""
    cwd = Path.cwd()
    for _ in range(5):
        openspec = cwd / "openspec" / "changes"
        if openspec.is_dir():
            return openspec
        if cwd.parent == cwd:
            break
        cwd = cwd.parent
    return None


def _extract_proposal(proposal_path: Path) -> dict:
    """Parse proposal.md and extract structured fields."""
    try:
        text = proposal_path.read_text()
    except Exception:
        return {}

    result = {"file": str(proposal_path)}

    # Extract title (first # heading)
    m = re.search(r'^#\s+(.+)', text, re.MULTILINE)
    if m:
        result["title"] = m.group(1).strip().removeprefix("Proposal: ").removeprefix("Proposal ")

    # Extract Why section
    m = re.search(r'## Why\n+(.+?)(?=\n##|\Z)', text, re.DOTALL)
    if m:
        result["why"] = m.group(1).strip()

    # Extract What Changes section
    m = re.search(r'## What Changes\n+(.+?)(?=\n##|\Z)', text, re.DOTALL)
    if m:
        result["what"] = m.group(1).strip()

    # Extract the HDU-ID from directory name
    hdu_dir = proposal_path.parent.name
    result["hdu_id"] = hdu_dir

    return result


def generate_changelog(output_path: Optional[str] = None, version: Optional[str] = None) -> int:
    """Generate CHANGELOG.md from openspec/changes/ HDUs.

    Scans each HDU-* directory, reads proposal.md, and generates a
    user-facing changelog with Why and What Changes sections per feature.

    Args:
        output_path: Where to write the changelog. Defaults to cwd/CHANGELOG.md.
        version: Release version tag (e.g., v0.2.0). If omitted, uses "Unreleased".

    Returns 0 on success, 1 on error.
    """
    openspec = _find_openspec_dir()
    if openspec is None:
        print("Error: openspec/changes/ not found. Run from a Gingx project root.")
        return 1

    # Discover HDUs
    hdus = []
    for d in sorted(openspec.iterdir()):
        if not d.is_dir():
            continue
        proposal = d / "proposal.md"
        if proposal.exists():
            parsed = _extract_proposal(proposal)
            if parsed:
                hdus.append(parsed)

    if not hdus:
        print("No HDU proposals found in openspec/changes/")
        return 1

    # Generate changelog
    version_str = version or "Unreleased"
    lines = [
        "# Changelog — Gingx Ecosystem",
        "",
        "Generated by `gingx-sdd changelog` from `openspec/changes/`.",
        "",
        "---",
        "",
        f"## {version_str}",
        "",
    ]

    for hdu in hdus:
        title = hdu.get("title", hdu.get("hdu_id", "Unknown"))
        hdu_id = hdu.get("hdu_id", "")

        lines.append(f"### {title} ({hdu_id})")
        lines.append("")

        why = hdu.get("why", "")
        if why:
            # Take just the first line of the why
            first_line = why.split("\n")[0].strip()
            lines.append(f"**Why:** {first_line}")
            lines.append("")

        what = hdu.get("what", "")
        if what:
            # Bulletize the what section
            for line in what.split("\n"):
                line = line.strip()
                if line.startswith("- "):
                    lines.append(f"  {line}")
                elif line and not line.startswith("#"):
                    lines.append(f"  - {line}")

        lines.append("")

    # Write
    out = Path(output_path) if output_path else Path.cwd() / "CHANGELOG.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"Changelog written to {out}")
    print(f"  {len(hdus)} HDUs indexed")
    return 0
